### ISSUE TITLE
Spawn Effects not working

### ISSUE THREAD

**Issue by jaku** [tesla1889tv/ControlValleyMod#15]
The spawn effects aren't working for a user. Everything else works but running a spawn effect makes the mod disconnect.

The only thing that might be odd is that they have a swedish install of windows.

**Comment by BambooleanLogic** [comment]
I downloaded a bunch of Windows language packs and ran some experiments.

It appears that the problem is not fundamentally caused by your system language, but specifically which "Regional format" setting you use. Below are my findings:

- Danish
    - Broken for Denmark, Greenland
- English
    - Works for Canada, Ireland, New Zealand, Puerto Rico, UK, US
- French
    - Broken for Canada, France, Switzerland
- German
    - Works for Switzerland
    - Broken for Austria and Germany
- Spanish
    - Works for Mexico, Puerto Rico, US
    - Broken for Spain, Venezuela
- Swedish
    - Broken for Åland, Finland, Sweden

**Comment by BambooleanLogic** [comment]
I can't claim to know the first thing about Stardew Valley modding, but I noticed something as I was digging through the code.

Assuming that [this decompilation of Stardew Valley](https://github.com/AdamMcIntosh/StawdewValley/) is sufficiently accurate, it seems like all the threads it creates contains the following line:

```csharp
Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
```

I'm also noticing that the threads created by this mod do not appear to contain similar assignments. I therefore posit that Stardew Valley itself might behave in unpredictable ways if called from threads that haven't had their cultures normalized.
