### ISSUE TITLE
QA Check 2021-04-25

### ISSUE THREAD

**Issue by KatDevsGames** [tesla1889tv/ControlValleyMod#6]
Bugs:
1: Darkness effect does not work during rain but charges viewer anyway.
2: Warp to mines/railroad/forest strands player with obstruction on walking back. No way to progress. (Remove obstruction?)
3: Warping during fishing/sleeping/etc can lock player.
4: Warping to town when player cannot enter (egg festival setup/etc) fails to warp player but charges viewer anyway.

Feedback
1: Early deaths cause loss of sword with no way to retrieve new sword for extended amount of time (grant adventurer's guild membership?).
2: Test audience requested Spawn Bomb effect.
3: Test audience requested spawn enemy swarm (e.g. 10x bats at once).

**Comment by nothing2see** [comment]
Segregated into multiple issues
